spring.application.name=ledger-system
spring.datasource.url=jdbc:postgresql://localhost:5432/ledger_system
spring.datasource.username=postgres
spring.datasource.password=kashvi120708

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379